### ISSUE TITLE
LSP sub menu options are all grayed out (except for 'go to symbol ref' & ' find symbol def'

### ISSUE THREAD

**Issue by iddinev** [sublimelsp/LSP-bash#11]
First of all - sorry if this is a configuration issue on my part and not an issue with the package itself - I am new to both Sublime and LSPs.

I installed the LSP following the doc's to the best of my advice - upon start the LSP is listed as up and running and Sublime's log says that there were no issues with the startup of the program or any of the packages.
Then when I right click on a variable inside a bash file to access the LSP sub menu all the options are grayed out except for:
'Go To Symbol Reference' & 'Find Symbol Definition'. 
I have not added any configs of my own - the LSP & Sublime are using their default supplied configs.
Can anybody shed some light into this, or help me continue debugging ?

**Comment by jfcherng** [comment]
Not all server support all features defined by the LSP protocol.

**Comment by iddinev** [comment]
Is there a way to check what features are exposed to Sublime, from a given LSP, from within Sublime ?

**Comment by jfcherng** [comment]
I am not sure but I believe if the server implements it, then it won't be grey out in ST.

**Comment by iddinev** [comment]
Thank you for the info. The issue is no longer needed.
