### ISSUE TITLE
Copy-paste mistake

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-bash#2]
https://github.com/sublimelsp/LSP-bash/blob/bd72521be2b1b59fb6967430c6f553eb8395e86c/plugin.py#L31

Someone should write a NodeBasedLanguageHandler base class by the way. A lot of these helper packages are starting to look the same :)

**Comment by jfcherng** [comment]
Ha, nice cache. Didn't find it since the plugin still works even with a wrong class name :laughing:

**Comment by jfcherng** [comment]
Fixed in https://github.com/sublimelsp/LSP-bash/commit/56a8fc8eb866d7fb262f559d0a0278f609446d4e
