### ISSUE TITLE
Configuration errors

### ISSUE THREAD

**Issue by psydvl** [sublimelsp/LSP-bash#43]
## Details
- [ ] Environment variable configuration is being deprecated
- [ ] `updateConfiguration` failing
- [ ] ~Not string env variable not expected~

In other words, there is no way to set `backgroundAnalysisMaxFiles` or `BACKGROUND_ANALYSIS_MAX_FILES`

## LSP log panel
```
::  -> LSP-bash initialized: {}
::  -> LSP-bash workspace/didChangeConfiguration: {'settings': {'backgroundAnalysisMaxFiles': 5}}
LSP-bash: Environment variable configuration is being deprecated, please use workspace configuration. The following environment variables were used: shellcheckPath
:: <-  LSP-bash window/logMessage: {'type': 2, 'message': 'Environment variable configuration is being deprecated, please use workspace configuration. The following environment variables were used: shellcheckPath'}
:: <-- LSP-bash client/registerCapability(0): {'registrations': [{'id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', 'method': 'workspace/didChangeConfiguration', 'registerOptions': {'section': 'bashIde'}}]}
:: >>> LSP-bash 0: None
:: <-- LSP-bash workspace/configuration(1): {'items': [{'section': 'bashIde'}]}
:: >>> LSP-bash 1: [None]
LSP-bash: updateConfiguration: failed with [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "null",
    "path": [],
    "message": "Expected object, received null"
  }
]
:: <-  LSP-bash window/logMessage: {'type': 2, 'message': 'updateConfiguration: failed with [\n  {\n    "code": "invalid_type",\n    "expected": "object",\n    "received": "null",\n    "path": [],\n    "message": "Expected object, received null"\n  }\n]'}
```

## ~Env variable setting int~

```json
{
	"env": {
		"BACKGROUND_ANALYSIS_MAX_FILES": 0,
	},
}
```
Raise next error
![image](https://user-images.githubusercontent.com/43755002/207718269-82885e24-1525-4648-aa3d-c6c123e1499f.png)

**Comment by jfcherng** [comment]
Logically, `env` variables should always be strings. So if you set it to string and it doesn't work, I would say it's a bug on the server side.

**Comment by psydvl** [comment]
Okay, this seems bash-language-server side problem, I'll open issue there.
But I still can't set any option via "initializationOptions" or "settings", while with since "Environment variable configuration is being deprecated" it is expected to work

Next config will not set shellcheck path
```json
{
	"env": {},
	"initializationOptions": {
		"shellcheckPath": "/home/nixi/App/shellcheck",
	},
	"settings": {
		"shellcheckPath": "/home/nixi/App/shellcheck",
	},
}
```

**Comment by jfcherng** [comment]
> But I still can't set any option via "initializationOptions" or "settings", while with since "Environment variable configuration is being deprecated" it is expected to work

After reading server source codes, the way it loads settings is a bit weird.

```js
{
    "settings": {
        "bashIde": {
            "shellcheckPath": "/home/nixi/App/shellcheck",
        },
    },
}
```

**Comment by jfcherng** [comment]
Fixed by migrating settings from `env` to `settings`. And `1.1.16` has been released to address this issue.
